const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.bound,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.Signal,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.InstanceSignal,
		C3.Plugins.Sprite.Cnds.OnInstanceSignal,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Projétil: 0},
	{BackGround: 0},
	{NomeDoJogo: 0},
	{Vida: 0},
	{MoverPara: 0},
	{RestritoAoLayout: 0},
	{Player: 0},
	{Toque: 0},
	{Mouse: 0},
	{Sprite2: 0},
	{Sprite: 0},
	{TiroPlayer: 0},
	{Partículas: 0},
	{TiroInimigo: 0},
	{Sprite3: 0},
	{BossLife: 0},
	{Sprite4: 0},
	{TiroInimigo2: 0},
	{TiroBoss: 0},
	{"9secções": 0},
	{Sprite5: 0},
	{Texto: 0},
	{Vidas: 0},
	{X: 0},
	{Pontos: 0},
	{Menu: 0},
	{kill: 0},
	{boss: 0},
	{CanSpawn: 0}
];

self.InstanceType = {
	BackGround: class extends self.ITiledBackgroundInstance {},
	NomeDoJogo: class extends self.ITextInstance {},
	Player: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiroPlayer: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	TiroInimigo: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiroInimigo2: class extends self.ISpriteInstance {},
	TiroBoss: class extends self.ISpriteInstance {},
	_9secções: class extends self.I9PatchInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Vidas: class extends self.ITextInstance {},
	X: class extends self.ITextInstance {},
	Pontos: class extends self.ITextInstance {}
}